version: '3'

services:
  laravel-app:
    image: thecodingmachine/php:8.2-v4-apache-node14
    container_name: laravel-app
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
    environment:
      # Laravel specific environment variables
      - APP_NAME=Laravel
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - LOG_CHANNEL=stack
      - DB_CONNECTION=sqlite
      # Other environment variables
    working_dir: /var/www/html
